name: Build/release

on:
  push:
    ## Run on tags starting with `v*`
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    continue-on-error: false
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: 'Zip folder'
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: "agregore-history-${{github.ref_name}}.zip"
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: 'Upload Release'
        uses: ncipollo/release-action@v1.12.0
        with:
           artifacts: "agregore-history-${{github.ref_name}}.zip"
           token: ${{ secrets.GITHUB_TOKEN }}
           draft: true
           allowUpdates: true
